// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Notification struct {
	ID            int64
	TransactionID int32
	CreatedAt     sql.NullTime
}

type Transaction struct {
	ID         int32
	Value      string
	FromUserID int32
	ToUserID   int32
	CreatedAt  sql.NullTime
}

type UsersBalance struct {
	ID        int64
	Balance   sql.NullString
	UserID    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
