version: "3"

services:
  auth:
    build:
      context: ./../auth
      dockerfile: ./../auth/build/Dockerfile
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql_database:3306
      TOKEN_SECRET: ${TOKEN_SECRET}
  listener:
    build:
      context: ./../listener
      dockerfile: ./../listener/build/Dockerfile
    restart: always
  broker:
    build:
      context: ./../broker
      dockerfile: ./../broker/build/Dockerfile
    restart: always
    ports:
      - "8082:80"
  transaction:
    build:
      context: ./../transaction
      dockerfile: ./../transaction/build/Dockerfile
    restart: always
    ports:
      - "8081:80"
    environment:
      TRANSACTION_DB_USER: ${TRANSACTION_DB_USER}
      TRANSACTION_DB_PASSWORD: ${TRANSACTION_DB_PASSWORD}
      TRANSACTION_DB_HOST: mysql_transaction_database:3306


  mysql_database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "auth"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database-data/mysql:/var/lib/mysql
  
  mysql_transaction_database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "transaction"
      MYSQL_USER: ${TRANSACTION_DB_USER}
      MYSQL_PASSWORD: ${TRANSACTION_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TRANSACTION_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./database-data/mysql-transaction:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql_database
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '8079:80'

  phpmyadmin_transaction:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql_transaction_database
      MYSQL_ROOT_PASSWORD: ${TRANSACTION_DB_PASSWORD}
    ports:
      - '8078:80'
    depends_on:
      - mysql_transaction_database

  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
     - ./database-data/rabbitmq/:/var/lib/rabbitmq/  
